version: '3.8'
services:
  # kafka:
  #   build:
  #     context: ./build/kafka-kraft
  #     args:
  #       KAFKA_IMAGE: ${KAFKA_IMAGE}
  #       KAFKA_IMAGE_TAG: ${KAFKA_IMAGE_TAG}
  #   restart: ${KAFKA_RESTART_POLICY}
  #   hostname: ${KAFKA_HOSTNAME}
  #   container_name: ${KAFKA_CONTAINER_NAME}
  #   ports:
  #     - 0.0.0.0:${KAFKA_WORKERS_PORT}:${KAFKA_WORKERS_PORT}
  #     - 0.0.0.0:${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}
  #   environment:
  #     KAFKA_KRAFT_MODE: ${KAFKA_KRAFT_MODE}
  #     KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
  #     KAFKA_NODE_ID: ${KAFKA_NODE_ID}
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
  #     KAFKA_LISTENERS: ${KAFKA_LISTENERS}
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
  #     KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
  #     KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
  #     KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS} # Corectat pentru acces intern
  #     KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
  #     KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
  #     CLUSTER_ID: ${CLUSTER_ID}
  #   volumes:
  #     - ./volumes/kafka-kraft/data:${KAFKA_VOLUME}

  # kafdrop:
  #   build:
  #     context: ./build/kafka-kraft
  #     args:
  #       KAFKA_IMAGE: ${KAFDROP_IMAGE}
  #       KAFKA_IMAGE_TAG: ${KAFDROP_IMAGE_TAG}

  #   restart: ${KAFDROP_RESTART_POLICY}
  #   hostname: ${KAFDROP_HOSTNAME}
  #   container_name: ${KAFDROP_CONTAINER_NAME}
  #   ports:
  #     - 0.0.0.0:${KAFDROP_PORT}:${KAFDROP_PORT}
  #   environment:
  #     KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
  #   depends_on:
  #     - "kafka"

  kafka:
    build:
      context: ./build/ubuntu-net
    container_name: kafka
    network_mode: none
    privileged: true
    command: sleep infinity

  kafdrop:
    build:
      context: ./build/ubuntu-net
    container_name: kafdrop
    network_mode: none
    privileged: true
    command: sleep infinity

  worker1:
    build:
      context: ./build/ubuntu-net
    container_name: worker1
    network_mode: none
    privileged: true
    command: sleep infinity

  worker2:
    build:
      context: ./build/ubuntu-net
    container_name: worker2
    network_mode: none
    privileged: true
    command: sleep infinity

  worker3:
    build:
      context: ./build/ubuntu-net
    container_name: worker3
    network_mode: none
    privileged: true
    command: sleep infinity

  sw5:
    build:
      context: ./build/openvswitch
      # args:
      #   BIND9_IMAGE: ${BIND9_IMAGE}
      #   BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
      # restart: ${BIND9_RESTART_POLICY}
    privileged: true
    hostname: "sw5"
    container_name: "sw5"
    network_mode: none
