services:
  dns:
    build:
      context: ./build/dns
      args:
        BIND9_IMAGE: ${BIND9_IMAGE}
        BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
    restart: ${BIND9_RESTART_POLICY}
    hostname: ${BIND9_HOSTNAME}
    container_name: ${BIND9_CONTAINER_NAME}
    network_mode: none
    privileged: true

  dns_collector:
    build:
      context: ./build/collector
      args:
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
    container_name: ${DNS_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true
    restart: unless-stopped
    environment:
      LAYER: "top"
      CAPTURE_INTERFACE: ${CAPTURE_INTERFACE}
      CAPTURE_DURATION: ${CAPTURE_DURATION}
      WAIT_FOR_IP: ${DNS_COL_SW1_IP}
      MINIO_ENDPOINT: ${MINIO_SW5_IP}:${MINIO_SERVER_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_TOP_LAYER_BUCKET}
      KAFKA_BROKER: ${KAFKA_SW5_IP}:${KAFKA_WORKERS_PORT}
      KAFKA_TOPIC: ${MINIO_TOP_LAYER_BUCKET}

  proxy:
    build:
      context: ./build/proxy
      args:
        NGINX_IMAGE_TAG: ${NGINX_IMAGE_TAG}
        NGINX_IMAGE: ${NGINX_IMAGE}
    restart: ${NGINX_RESTART_POLICY}
    hostname: ${NGINX_HOSTNAME}
    container_name: ${NGINX_CONTAINER_NAME}
    network_mode: none
    privileged: true

  proxy_collector:
    build:
      context: ./build/collector
      args:
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
    container_name: ${PROXY_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true
    restart: unless-stopped
    environment:
      LAYER: "inter"
      CAPTURE_INTERFACE: ${CAPTURE_INTERFACE}
      CAPTURE_DURATION: ${CAPTURE_DURATION}
      WAIT_FOR_IP: ${PROXY_COL_SW2_IP}
      MINIO_ENDPOINT: ${MINIO_SW5_IP}:${MINIO_SERVER_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_INTERMEDIATE_BUCKET}
      KAFKA_BROKER: ${KAFKA_SW5_IP}:${KAFKA_WORKERS_PORT}
      KAFKA_TOPIC: ${MINIO_INTERMEDIATE_BUCKET}

  webserver:
    build:
      context: ./build/webserver
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    restart: ${WEBSERVER_RESTART_POLICY}
    hostname: ${WEBSERVER_HOSTNAME}
    container_name: ${WEBSERVER_CONTAINER_NAME}
    network_mode: none
    privileged: true
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      WEBSERVER_HOST: ${WEBSERVER_HOST}
      WEBSERVER_DEBUG: ${WEBSERVER_DEBUG}

  web_collector:
    build:
      context: ./build/collector
      args:
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
    container_name: ${WEB_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true
    restart: unless-stopped
    environment:
      LAYER: "bottom"
      CAPTURE_INTERFACE: ${CAPTURE_INTERFACE}
      CAPTURE_DURATION: ${CAPTURE_DURATION}
      WAIT_FOR_IP: ${SERVICE_COL_SW3_IP}
      MINIO_ENDPOINT: ${MINIO_SW5_IP}:${MINIO_SERVER_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BOTTOM_LAYER_BUCKET}
      KAFKA_BROKER: ${KAFKA_SW5_IP}:${KAFKA_WORKERS_PORT}
      KAFKA_TOPIC: ${MINIO_BOTTOM_LAYER_BUCKET}

  ryu:
    build:
      context: ./build/ryu-controller
      args:
        SDN_IMAGE_TAG: ${SDN_IMAGE_TAG}
        SDN_IMAGE: ${SDN_IMAGE}
    restart: ${SDN_RESTART_POLICY}
    privileged: true
    hostname: ${SDN_HOSTNAME}
    container_name: ${SDN_CONTAINER_NAME}
    network_mode: host
    environment:
      KAFKA_BROKER: ${KAFKA_SW5_IP}:${KAFKA_WORKERS_PORT}
      KAFKA_ALERT_TOPIC: ${KAFKA_ALERT_TOPIC}
      BLOCK_HARD_TIMEOUT: ${BLOCK_HARD_TIMEOUT}
      BLOCK_PRIORITY: ${BLOCK_PRIORITY}
      BLOCK_WHITELIST: ${BLOCK_WHITELIST}
      LAYER_DATAPATH_MAP: ${LAYER_DATAPATH_MAP}
      OFP_LISTEN_PORT: ${SDN_PORT}
      REST_PORT: ${SDN_PORT_REST_API}

  sw1:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW1_HOSTNAME}
    container_name: ${OPENVSWITCH_SW1_CONTAINER_NAME}
    network_mode: none

  sw2:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW2_HOSTNAME}
    container_name: ${OPENVSWITCH_SW2_CONTAINER_NAME}
    network_mode: none

  sw3:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW3_HOSTNAME}
    container_name: ${OPENVSWITCH_SW3_CONTAINER_NAME}
    network_mode: none

  sw4:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW4_HOSTNAME}
    container_name: ${OPENVSWITCH_SW4_CONTAINER_NAME}
    network_mode: none
