version: '3.8'
services:
  kafka:
    build:
      context: ./build/kafka-kraft
      args:
        KAFKA_IMAGE: ${KAFKA_IMAGE}
        KAFKA_IMAGE_TAG: ${KAFKA_IMAGE_TAG}
    restart: ${KAFKA_RESTART_POLICY}
    hostname: ${KAFKA_HOSTNAME}
    container_name: ${KAFKA_CONTAINER_NAME}
    network_mode: none 
    privileged: true
    environment:
      KAFKA_KRAFT_MODE: ${KAFKA_KRAFT_MODE}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - ./volumes/kafka-kraft/data:${KAFKA_VOLUME}

  kafdrop:
    build:
      context: ./build/kafdrop
      args:
        KAFDROP_IMAGE: ${KAFDROP_IMAGE}
        KAFDROP_IMAGE_TAG: ${KAFDROP_IMAGE_TAG}
    restart: ${KAFDROP_RESTART_POLICY}
    hostname: ${KAFDROP_HOSTNAME}
    container_name: ${KAFDROP_CONTAINER_NAME}
    network_mode: none
    privileged: true
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
      SERVER_PORT: ${KAFDROP_PORT}
  minio:
    context: ./build/minio
    args:
      MINIO_IMAGE: ${MINIO_IMAGE}
      MINIO_IMAGE_TAG: ${MINIO_IMAGE_TAG}
    hostname: ${MINIO_HOSTNAME}
    container_name: ${MINIO_CONTAINER_NAME}
    network_mode: none
    privileged: true
    environment:
      MINIO_ROOT_USER:      ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD:  ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL:     ${MINIO_SERVER_URL}
    volumes:
      - ./volumes/minio/data:/data

  worker1:
    build:
      context: ./build/ubuntu-net
    container_name: worker1
    network_mode: none
    privileged: true
    command: sleep infinity

  worker2:
    build:
      context: ./build/ubuntu-net
    container_name: worker2
    network_mode: none
    privileged: true
    command: sleep infinity

  worker3:
    build:
      context: ./build/ubuntu-net
    container_name: worker3
    network_mode: none
    privileged: true
    command: sleep infinity

  sw5:
    build:
      context: ./build/openvswitch
    privileged: true
    hostname: "sw5"
    container_name: "sw5"
    network_mode: none
