version: '3.8'
services:
  dns:
    build:
      context: ./build/dns
      args:
        BIND9_IMAGE: ${BIND9_IMAGE}
        BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
    restart: ${BIND9_RESTART_POLICY}
    hostname: ${BIND9_HOSTNAME}
    container_name: ${BIND9_CONTAINER_NAME}
    network_mode: none
    privileged: true

  # example:
  #   build:
  #     context: ./build/ubuntu-net
  #   container_name: dns
  #   network_mode: none
  #   privileged: true
  #   command: sleep infinity

  dns_collector:
    build:
      context: ./build/dns-collector
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: dns_collector
    network_mode: none
    privileged: true
    command: sleep infinity

  proxy:
    build:
      context: ./build/proxy
      args:
        NGINX_IMAGE_TAG: ${NGINX_IMAGE_TAG}
        NGINX_IMAGE: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER_NAME}
    network_mode: none
    privileged: true
    restart: ${NGINX_RESTART_POLICY}
    #command: sleep infinity

  proxy_collector:
    build:
      context: ./build/proxy-collector
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: proxy_collector
    network_mode: none
    privileged: true
    command: sleep infinity

  webserver:
    build:
      context: ./build/webserver
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: ${WEBSERVER_CONTAINER_NAME}
    network_mode: none
    privileged: true
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      WEBSERVER_HOST: ${WEBSERVER_HOST}
      WEBSERVER_DEBUG: ${WEBSERVER_DEBUG}
    #command: sleep infinity

  web_collector:
    build:
      context: ./build/ubuntu-net
    container_name: web_collector
    network_mode: none
    privileged: true
    #command: sleep infinity

  ryu:
    build:
      context: ./build/ryu-controller
      args:
        SDN_IMAGE_TAG: ${SDN_IMAGE_TAG}
        SDN_IMAGE: ${SDN_IMAGE}
    restart: ${SDN_RESTART_POLICY}
    privileged: true
    hostname: "ryu"
    container_name: "ryu"
    network_mode: host
    ports:
      - "0.0.0.0:6633:6633"
      - "0.0.0.0:8080:8080"

  sw1:
    build:
      context: ./build/openvswitch
      # args:
      #   BIND9_IMAGE: ${BIND9_IMAGE}
      #   BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
      # restart: ${BIND9_RESTART_POLICY}
    privileged: true
    hostname: "sw1"
    container_name: "sw1"
    network_mode: none

  sw2:
    build:
      context: ./build/openvswitch
      # args:
      #   BIND9_IMAGE: ${BIND9_IMAGE}
      #   BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
      # restart: ${BIND9_RESTART_POLICY}
    privileged: true
    hostname: "sw2"
    container_name: "sw2"
    network_mode: none

  sw3:
    build:
      context: ./build/openvswitch
      # args:
      #   BIND9_IMAGE: ${BIND9_IMAGE}
      #   BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
      # restart: ${BIND9_RESTART_POLICY}
    privileged: true
    hostname: "sw3"
    container_name: "sw3"
    network_mode: none

  sw4:
    build:
      context: ./build/openvswitch
      # args:
      #   BIND9_IMAGE: ${BIND9_IMAGE}
      #   BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
      # restart: ${BIND9_RESTART_POLICY}
    privileged: true
    hostname: "sw4"
    container_name: "sw4"
    network_mode: none
