version: "3.8"
services:
  dns:
    build:
      context: ./build/dns
      args:
        BIND9_IMAGE: ${BIND9_IMAGE}
        BIND9_IMAGE_TAG: ${BIND9_IMAGE_TAG}
    restart: ${BIND9_RESTART_POLICY}
    hostname: ${BIND9_HOSTNAME}
    container_name: ${BIND9_CONTAINER_NAME}
    network_mode: none
    privileged: true

  dns_collector:
    build:
      context: ./build/dns-collector
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: ${DNS_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true

  proxy:
    build:
      context: ./build/proxy
      args:
        NGINX_IMAGE_TAG: ${NGINX_IMAGE_TAG}
        NGINX_IMAGE: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER_NAME}
    network_mode: none
    privileged: true
    restart: ${NGINX_RESTART_POLICY}


  proxy_collector:
    build:
      context: ./build/proxy-collector
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: ${PROXY_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true

  webserver:
    build:
      context: ./build/webserver
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: ${WEBSERVER_CONTAINER_NAME}
    network_mode: none
    privileged: true
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      WEBSERVER_HOST: ${WEBSERVER_HOST}
      WEBSERVER_DEBUG: ${WEBSERVER_DEBUG}

  web_collector:
    build:
      context: ./build/service-collector
      args:
        WEBSERVER_IMAGE_TAG: ${WEBSERVER_IMAGE_TAG}
        WEBSERVER_IMAGE: ${WEBSERVER_IMAGE}
    container_name: ${WEB_COLLECTOR_CONTAINER_NAME}
    network_mode: none
    privileged: true

  ryu:
    build:
      context: ./build/ryu-controller
      args:
        SDN_IMAGE_TAG: ${SDN_IMAGE_TAG}
        SDN_IMAGE: ${SDN_IMAGE}
    restart: ${SDN_RESTART_POLICY}
    privileged: true
    hostname: ${SDN_HOSTNAME}
    container_name: ${SDN_CONTAINER_NAME}
    network_mode: host
    ports:
      - "${SDN_HOST}:${SDN_PORT}:${SDN_PORT}"
      - "${SDN_REST_API_HOST}:${SDN_PORT_REST_API}:${SDN_PORT_REST_API}"

  sw1:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW1_HOSTNAME}
    container_name: ${OPENVSWITCH_SW1_CONTAINER_NAME}
    network_mode: none

  sw2:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW2_HOSTNAME}
    container_name: ${OPENVSWITCH_SW2_CONTAINER_NAME}
    network_mode: none

  sw3:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW3_HOSTNAME}
    container_name: ${OPENVSWITCH_SW3_CONTAINER_NAME}
    network_mode: none

  sw4:
    build:
      context: ./build/openvswitch
      args:
        OPENVSWITCH_IMAGE_TAG: ${OPENVSWITCH_IMAGE_TAG}
        OPENVSWITCH_IMAGE: ${OPENVSWITCH_IMAGE}
    privileged: true
    hostname: ${OPENVSWITCH_SW4_HOSTNAME}
    container_name: ${OPENVSWITCH_SW4_CONTAINER_NAME}
    network_mode: none
