name: Normalize line endings

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  normalize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert CRLF to LF using sed
        shell: bash
        run: |
          echo "Searching for CRLF files..."
          files=$(grep -Ilr $'\r' . --exclude-dir=.git || true)
          if [[ -z "$files" ]]; then
            echo "No CRLF endings found."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Normalizing line endings..."
            echo "$files" | while read -r f; do
              printf "  -> %s\n" "$f"
              sed -i 's/\r$//' "$f"
            done
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Check for changes
        run: |
          if [[ "$(git status --porcelain)" ]]; then
            echo "Files changed:"
            git status --short
          else
            echo "No files changed."
          fi

      - name: Commit normalized files
        if: env.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Normalize line endings (CRLF → LF)"
          git push
